include::{commondir}/common-spockinjavaapp.adoc[]

Create a tests which verifies the user authentication flow via Basic Auth.

[source,groovy]
.src/test/groovy/demo/BasicAuthSpec.groovy
----
include::{sourceDir}/src/test/groovy/demo/BasicAuthSpec.groovy[]
}
----

<1> The AutoCleanup extension makes sure the `close()` method of an object (e.g. `EmbeddedServer`) is called each time a feature method is finished
<2> To run the application from a unit test you can use the http://docs.micronaut.io/snapshot/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface
<3> Register a `RxClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<4> Creating HTTP Requests is easy thanks to Micronaut's fluid API.
<5> If you attempt to access a secured endpoint without authentication, 401 is returned
<6> By using `basicAuth` method, you populate the `Authorization` header with user-id:password pairs, encoded using Base64.
<7> Micronaut's `HttpClient` simplifies parsing HTTP response payload to Java objects. In this example, we parse the response to `String`.
<8> Use `.body()` to retrieve the parsed payload.
